import Footer from "@/components/Footer";

import Head from "next/head";
import { Inter } from "next/font/google";
import Blogs from "@/components/blog_section/Blogs";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  return (
    <>
      <Head>
        <title>"HealthHub" let's lead a healthy life </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Blogs></Blogs>
    </>
  );
}
